Repository HHS/OPRE-OPS, pull requests merged in 2022-08, with the labels that each got.

#394 376: Uvicorn & Gunicorn
  backend/Dockerfile
  backend/Pipfile
  backend/Pipfile.lock
  backend/opre_ops/django_config/asgi.py
  backend/opre_ops/django_config/wsgi.py
  docker-compose.yml
  manifest.yml
Labels: infrastructure, tech-debt

#396 Issue 376 portfolio schema
  backend/opre_ops/ops_site/cans/models.py
  backend/opre_ops/ops_site/fixtures/fake_data.json
  backend/opre_ops/ops_site/migrations/0002_significant_model_updates.py
  backend/opre_ops/ops_site/migrations/0003_portfolio_commonaccountingnumber_portfolio.py
  backend/opre_ops/ops_site/portfolios/__init__.py
  backend/opre_ops/ops_site/portfolios/controller.py
  backend/opre_ops/ops_site/portfolios/models.py
  backend/opre_ops/ops_site/urls.py
  backend/tests/ops_site/cans/test_can_controller.py
  backend/tests/ops_site/cans/test_can_models.py
  backend/tests/ops_site/portfolios/test_portfolio_controller.py
  backend/tests/ops_site/portfolios/test_portfolio_models.py
Labels: task

#393 Semgrep permission fix
  .github/workflows/ci.yml
  .github/workflows/security_semgrep.yml
Labels: tech-debt

#397 376: Only install non-dev dependencies when running in Docker
  .github/workflows/dev_deploy.yml
  frontend/Dockerfile
  frontend/package.json
  frontend/yarn.lock
Labels: tech-debt

#403 remove web-vitals
  frontend/package.json
  frontend/src/index.jsx
  frontend/src/reportWebVitals.js
  frontend/yarn.lock
Labels: dependencies, tech-debt

#406 Remove explicit eslint-plugin-react dependency
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#410 Issue 376 portfolio detail view
  .gitignore
  backend/opre_ops/ops_site/cans/models.py
  backend/opre_ops/ops_site/fixtures/fake_data.json
  backend/opre_ops/ops_site/migrations/0004_alter_commonaccountingnumber_portfolio.py
  backend/opre_ops/ops_site/portfolios/controller.py
  frontend/gulpfile.js
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/index.jsx
  frontend/src/pages/cans/list/CanList.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
  frontend/src/pages/portfolios/detail/getPortfolio.js
  frontend/src/pages/portfolios/detail/getPortfolio.test.js
  frontend/src/pages/portfolios/detail/portfolioDetailSlice.js
  frontend/src/pages/portfolios/list/PortfolioList.jsx
  frontend/src/store.js
  frontend/yarn.lock
Labels: task
