Repository HHS/OPRE-OPS, pull requests merged in 2024-06, with the labels that each got.

#2379 major upgrade flask to v3
  backend/ops_api/Pipfile
  backend/ops_api/Pipfile.lock
Labels: dependencies

#2361 perf: add component tests in favor of cypress
  frontend/cypress/e2e/components.cy.js
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.test.js
  frontend/src/components/UI/Accordion/Accordian.test.jsx
  frontend/src/components/UI/Modals/ConfirmationModal.jsx
  frontend/src/components/UI/Modals/ConfirmationModal.test.jsx
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.test.jsx
Labels: javascript, Improvement

#2374 feat: adds form validation to non-DRAFT BLIs
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/ops_api/tests/ops/can/test_services_component.py
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.test.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIAndSCs.test.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/tests/data.js
Labels: javascript

#2385 refactor: Improve budget line helper functions and add documentation
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/budgetLines.helpers.test.js
  frontend/src/tests/data.js
Labels: javascript

#2386 refactor: Update CreateBLIsAndSCs component to handle continueOverRid…
  frontend/cypress/e2e/editAgreement.cy.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
Labels: javascript

#2451 feat: ✨ adds StatusChangeReviewCards
  frontend/bun.lockb
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/api/opsAPI.test.js
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.test.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/index.js
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequests.d.ts
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/index.js
  frontend/src/components/ChangeRequests/TermTag/TermTag.jsx
  frontend/src/components/ChangeRequests/TermTag/TermTag.test.jsx
  frontend/src/components/ChangeRequests/TermTag/index.js
  frontend/src/helpers/changeRequests.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/hooks/lookup.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/pages/agreements/review/reviewAgreement.hooks.js
  frontend/src/tests/data.js
  frontend/src/tests/mocks.js
  frontend/src/tests/setupTests.js
Labels: javascript

#2460 feat: ✨ adds change requests to Alerts and Tooltip
  frontend/src/components/Agreements/DetailsTabs/index.js
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequests.d.ts
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/tests/setupTests.js
Labels: javascript

#2470 feat: ✨ Login page improvements
  frontend/src/pages/Login.jsx
Labels: javascript
