Repository HHS/OPRE-OPS, pull requests merged in 2024-05, with the labels that each got.

#2330 Ops 2239/refactor get response schema
  backend/openapi.yml
  backend/ops_api/ops/resources/agreements.py
  backend/ops_api/ops/resources/agreements_constants.py
  backend/ops_api/ops/schemas/agreements.py
  backend/ops_api/ops/schemas/budget_line_items.py
  backend/ops_api/ops/schemas/procurement_shops.py
  backend/ops_api/ops/schemas/product_service_code.py
  backend/ops_api/ops/schemas/projects.py
Labels: tech-debt

#2337 docs: updates docs and script for vitest coverage
  README.md
  frontend/package.json
Labels: documentation

#2326 feat: Add changeRequests Alerts
  frontend/jsconfig.json
  frontend/src/api/patchBudgetLineItems.js
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementChangesAlert.test.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementsChangesAlert.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/index.js
  frontend/src/components/Agreements/AgreementDetailsCards/AgreementTotalBudgetLinesCard.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/components/UI/Alert/Alert.test.jsx
  frontend/src/components/UI/Alert/SimpleAlert.jsx
  frontend/src/components/UI/Alert/SimpleAlert.test.jsx
  frontend/src/components/UI/Alert/alertSlice.js
  frontend/src/components/UI/Tag/StatusTagList.jsx
  frontend/src/hooks/use-alert.hooks.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
Labels: javascript

#2342 fix: Agreement Summary Cards in edit mode
  frontend/src/components/Agreements/AgreementBudgetLinesHeader.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/UI/Tag/StatusTag.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.helpers.js
Labels: javascript

#2267 feat: ✨Ops 2193/FE round one
  backend/ops_api/ops/schemas/budget_line_items.py
  frontend/cypress/e2e/components.cy.js
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/editAgreement.cy.js
  frontend/jsconfig.json
  frontend/src/api/patchBudgetLineItems.js
  frontend/src/api/postBudgetLineItems.js
  frontend/src/components/Agreements/AgreementBudgetLinesHeader.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementChangesAlert.test.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementsChangesAlert.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/index.js
  frontend/src/components/Agreements/AgreementDetailsCards/AgreementTotalBudgetLinesCard.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.hooks.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.test.js
  frontend/src/components/BudgetLineItems/ChangeIcons/ChangeIcons.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIAndSCs.test.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/suite.js
  frontend/src/components/ServicesComponents/ServicesComponentAccordion/ServicesComponentAccordion.jsx
  frontend/src/components/ServicesComponents/ServicesComponents.hooks.js
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/components/UI/Alert/Alert.test.jsx
  frontend/src/components/UI/Alert/SimpleAlert.jsx
  frontend/src/components/UI/Alert/SimpleAlert.test.jsx
  frontend/src/components/UI/Alert/alertSlice.js
  frontend/src/components/UI/CurrencyInput/CurrencyInput.jsx
  frontend/src/components/UI/CurrencyInput/index.js
  frontend/src/components/UI/RadioButtonTile/RadioButtonTile.test.js
  frontend/src/components/UI/TableTag/TableTag.jsx
  frontend/src/components/UI/Tag/StatusTagList.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/hooks/budget-line.hooks.js
  frontend/src/hooks/use-alert.hooks.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/CreateAgreementFlow.jsx
  frontend/src/pages/agreements/CreateEditAgreement.jsx
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.helpers.js
Labels: javascript
