Repository HHS/OPRE-OPS, pull requests merged in 2024-10, with the labels that each got.

#2871 fix: adds keys to git ignore
  .gitignore
Labels: documentation

#2873 refactor: displays CAN obligate_by as MM/DD/YY
  backend/openapi.yml
  frontend/src/components/CANs/CANTable/CANTable.helpers.js
  frontend/src/components/CANs/CANTable/CANTable.helpers.test.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTable.test.jsx
  frontend/src/components/CANs/CANTable/CANTableHead.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/CANs/CANTypes.d.ts
Labels: javascript

#2875 initial ADR for PKI management
  docs/adr/027-pki-management.md
Labels: documentation

#2882 feat: ✨ adds FY Select to CANs List
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANBudgetSummary/CANBudgetSummary.jsx
  frontend/src/components/CANs/CANTable/CANTable.helpers.js
  frontend/src/components/CANs/CANTable/CANTable.helpers.test.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTable.test.jsx
  frontend/src/components/Layouts/TablePageLayout/TablePageLayout.jsx
  frontend/src/components/UI/FiscalYear/FiscalYear.jsx
  frontend/src/components/UI/FiscalYear/FiscalYear.module.css
  frontend/src/components/UI/FiscalYear/FiscalYear.test.js
  frontend/src/components/UI/FiscalYear/index.js
  frontend/src/components/UI/Select/Select.jsx
  frontend/src/components/Users/User.constants.js
  frontend/src/components/Users/UserTypes.d.ts
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
  frontend/src/pages/cans/list/CanList.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Labels: javascript

#2880 feat: role-based filtering of My CANs
  frontend/src/pages/cans/list/CanList.helpers.js
Labels: javascript

#2897 Ops 2737 azure ams fe config
  backend/ops_api/ops/environment/azure/prod.py
  frontend/src/helpers/backend.js
  frontend/vite-env/env.dev.local
  frontend/vite-env/env.production.local
  frontend/vite-env/env.stg.local
Labels: infrastructure

#2876 Lock Down Change Requests to DD and DDD
  backend/data_tools/data/user_data.json5
  backend/data_tools/src/import_static_data/import_data.py
  backend/ops_api/ops/resources/change_requests.py
  backend/ops_api/tests/auth_client.py
  backend/ops_api/tests/conftest.py
  backend/ops_api/tests/ops/agreement/test_agreement_history.py
  backend/ops_api/tests/ops/workflows/test_change_requests.py
Labels: bug

#2889 feat: ✨ adds active period filter to CANs list
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANActivePeriodComboBox/CANActivePeriodComboBox.jsx
  frontend/src/components/CANs/CANActivePeriodComboBox/index.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/UI/Form/ComboBox/ComboBox.jsx
  frontend/src/constants.js
  frontend/src/pages/cans/list/CANFilterButton/CANFiilterButton.jsx
  frontend/src/pages/cans/list/CANFilterButton/index.js
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#2883 Add CANFundingDetails Endpoint
  backend/alembic/versions/2024_10_03_2123-a5a535a5e285_adding_ops_events_for_canfundingdetails.py
  backend/alembic/versions/2024_10_09_1342-af64d84afb2e_re_adding_canfundingreceived_events.py
  backend/models/events.py
  backend/openapi.yml
  backend/ops_api/ops/resources/can_funding_details.py
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/ops/services/can_funding_details.py
  backend/ops_api/ops/urls.py
  backend/ops_api/ops/views.py
  backend/ops_api/tests/conftest.py
  backend/ops_api/tests/ops/can/test_can_funding_details.py
Labels: python

#2917 feat: ✨ adds filter CANList Pills (Tags)
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/UI/FilterTags/FilterTags.jsx
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.hooks.js
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.jsx
  frontend/src/pages/cans/list/CANFilterTags/index.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#2925 refactor: adds handleChange logix
  frontend/src/components/CANs/CANFYBudgetRangeSlider/CANFYBudgetRangeSlider.jsx
  frontend/src/components/UI/DoubleRangeSlider/DoubleRangeSlider.jsx
  frontend/src/components/UI/DoubleRangeSlider/index.js
Labels: javascript

#2934 style: 💅 UX Review fixes
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/UI/FilterTags/FilterTags.jsx
  frontend/src/constants.js
  frontend/src/pages/cans/list/CANFilterButton/CANFiilterButton.jsx
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
Labels: javascript

#2963 fix: update can funding summary openapi spec
  backend/openapi.yml
Labels: documentation

#2938 feat: ✨adds CANBudgetRangeSlider to CANs list
  frontend/Dockerfile
  frontend/bun.lockb
  frontend/cypress/e2e/canList.cy.js
  frontend/package.json
  frontend/src/api/opsAPI.js
  frontend/src/components/CANs/CANFYBudgetRangeSlider/CANFYBudgetRangeSlider.jsx
  frontend/src/components/CANs/CANFYBudgetRangeSlider/CANFYBudgetRangeSlider.test.jsx
  frontend/src/components/CANs/CANFYBudgetRangeSlider/index.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/UI/DoubleRangeSlider/DoubleRangeSlider.jsx
  frontend/src/components/UI/DoubleRangeSlider/DoubleRangeSlider.test.jsx
  frontend/src/components/UI/DoubleRangeSlider/index.js
  frontend/src/components/UI/FilterButton/FilterButton.jsx
  frontend/src/pages/cans/list/CANFilterButton/CANFiilterButton.jsx
  frontend/src/pages/cans/list/CANFilterButton/CANFilterButton.hooks.js
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.hooks.js
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.jsx
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#2964 fix: The current user's data was being overwritten
  backend/ops_api/ops/resources/budget_line_items.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
Labels: bug

#2974 feat: ✨ adds Budget Summary Card
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANFundingBar/CANFundingBar.jsx
  frontend/src/components/CANs/CANSummaryCards/CANSummaryCards.jsx
  frontend/src/components/CANs/CANSummaryCards/CANSummaryCards.test.jsx
  frontend/src/components/CANs/CANSummaryCards/index.js
  frontend/src/components/UI/SummaryCard/BudgetSummaryCard/BudgetSummaryCard.jsx
  frontend/src/components/UI/SummaryCard/BudgetSummaryCard/BudgetSummaryCard.test.jsx
  frontend/src/components/UI/SummaryCard/BudgetSummaryCard/index.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#3006 style: 💅 allow for neg values in Budget Card
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.jsx
Labels: Improvement
