Repository HHS/OPRE-OPS, pull requests merged in 2024-09, with the labels that each got.

#2773 OPS-1449 Refactor agreement/{id}/history endpoint
  backend/openapi.yml
  backend/ops_api/ops/urls.py
  backend/ops_api/tests/ops/agreement/test_agreement_history.py
  backend/ops_api/tests_manual/ops/test_change_requests.py
  frontend/src/api/getAgreementHistory.js
Labels: tech-debt, python, javascript

#2765 feat: ✨ data-viz updates
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/sass/uswds/styles.scss
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.test.jsx
  frontend/src/components/Agreements/AgreementDetailsCards/BLIsByFYSummaryCard/BLIsFYSummaryCard.helpers.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/BudgetLineItems/SummaryCardsSection/SummaryCardsSection.jsx
  frontend/src/components/CANs/CANFundingBar/CANFundingBar.jsx
  frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx
  frontend/src/components/CANs/CANFundingCard/CanFundingCard.test.jsx
  frontend/src/components/CANs/CanCard/CanCard.jsx
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/PortfolioFundingByBudgetStatus.jsx
  frontend/src/components/Portfolios/PortfolioHeader/PortfolioHeader.jsx
  frontend/src/components/UI/Accordion/Accordion.jsx
  frontend/src/components/UI/DocumentCard/DocumentCard.jsx
  frontend/src/components/UI/FilterButton/FilterButton.jsx
  frontend/src/components/UI/Hero/Hero.jsx
  frontend/src/components/UI/Hero/index.js
  frontend/src/components/UI/Hero/styles.module.css
  frontend/src/components/UI/HeroDescription/HeroDescription.jsx
  frontend/src/components/UI/ResponsiveDonutWithInnerPercent/ResponsiveDonutWithInnerPercent.jsx
  frontend/src/components/UI/RoundedBox/RoundedBox.jsx
  frontend/src/components/UI/RoundedBox/styles.module.css
  frontend/src/components/UI/Select/Select.jsx
  frontend/src/components/UI/SummaryCard/SummaryCard.jsx
  frontend/src/components/UI/Table/table.module.css
  frontend/src/components/UI/TableRowExpandable/TableRowExpandable.helpers.js
  frontend/src/components/UI/TableTag/TableTag.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/constants.js
  frontend/src/helpers/utils.js
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/list/AgreementsFilterButton.jsx
  frontend/src/pages/researchProjects/detail/ResearchProjectDetail.jsx
  frontend/src/uswds/css/styles.css
  frontend/src/uswds/css/styles.css.map
Labels: javascript

#2794 fix: only shows link for team members
  frontend/cypress/e2e/editAgreementAsBasicUser.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/pages/ErrorPage.jsx
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
Labels: bug, javascript

#2788 fix: fixes logic for displaying requestor name
  backend/data_tools/data/agreements_and_blin_data.json5
  frontend/cypress/e2e/statusChangeRequest.cy.js
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
Labels: bug, javascript

#2832 fix: 🛠️ adds missing validation on Agreement form
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditFormSuite.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/suite.js
  frontend/src/components/ServicesComponents/ContractTypeSelect/ContractTypeSelect.jsx
  frontend/src/components/ServicesComponents/ServiceReqTypeSelect/ServiceReqTypeSelect.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/review/suite.js
Labels: bug, javascript

#2804 feat: ✨ CANs List
  backend/data_tools/data/can_data.json5
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  docs/developers/frontend/types.md
  frontend/cypress/e2e/canList.cy.js
  frontend/cypress/e2e/loginPage.cy.js
  frontend/cypress/fixtures/initial-state.json
  frontend/jsconfig.json
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.jsx
  frontend/src/components/BudgetLineItems/BudgetLineTypes.d.ts
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTable.test.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.test.jsx
  frontend/src/components/CANs/CANTable/index.js
  frontend/src/components/CANs/CANTable/style.module.css
  frontend/src/components/CANs/CANTypes.d.ts
  frontend/src/components/CANs/CanTabs/CanTabs.jsx
  frontend/src/components/CANs/CanTabs/index.js
  frontend/src/components/ChangeRequests/ChangeRequests.hooks.js
  frontend/src/components/ChangeRequests/ChangeRequests.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsTypes.d.ts
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.jsx
  frontend/src/components/Layouts/TablePageLayout/TablePageLayout.jsx
  frontend/src/components/Portfolios/PortfolioTypes.d.ts
  frontend/src/components/Projects/ProjectTypes.d.ts
  frontend/src/components/Users/UserInfo/UserInfo.jsx
  frontend/src/components/Users/UserTypes.d.ts
  frontend/src/helpers/utils.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/index.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/cans/list/CanList.jsx
  frontend/src/pages/cans/list/CanList.test.jsx
  frontend/src/pages/cans/list/canListSlice.js
  frontend/src/pages/cans/list/getCanList.js
  frontend/src/pages/cans/list/getCanList.test.js
  frontend/src/store.js
  frontend/src/tests/data.js
  frontend/src/tests/mocks.js
Labels: javascript

#2843 chore: remove un-needed initial state?
  frontend/cypress/e2e/loginPage.cy.js
  frontend/cypress/fixtures/initial-state.json
Labels: javascript

#2846 fix: permission check for approve Agreement page
  .gitignore
  .vscode/settings.json
  backend/openapi.yml
  backend/ops_api/ops/schemas/budget_line_items.py
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/declineChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/support/e2e.js
  frontend/src/hooks/useToggle.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Labels: bug

#2854 Add endpoint for CANFundingBudgets
  backend/alembic/versions/2024_09_25_2046-d5610e0988b0_adding_canfundingbudget_meta_events.py
  backend/models/events.py
  backend/openapi.yml
  backend/ops_api/ops/resources/can_funding_budget.py
  backend/ops_api/ops/resources/cans.py
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/ops/services/can_funding_budget.py
  backend/ops_api/ops/urls.py
  backend/ops_api/ops/views.py
  backend/ops_api/tests/conftest.py
  backend/ops_api/tests/ops/can/test_can.py
  backend/ops_api/tests/ops/can/test_can_funding_budget.py
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Labels: task, tech-debt, python, Dev Backend Ready

#2858 feat: ✨Filter Change Requests
  backend/data_tools/data/portfolio_data.json5
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/cypress/e2e/declineChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtCardLevel.cy.js
  frontend/cypress/e2e/statusChangeRequest.cy.js
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestList.test.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/hooks/useChangeRequests.hooks.js
Labels: javascript
