Repository HHS/OPRE-OPS, pull requests merged in 2024-07, with the labels that each got.

#2479 feat: ✨adds Change Requests reviews at card level
  backend/openapi.yml
  frontend/cypress/e2e/agreementList.cy.js
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/cypress/e2e/requestApproval.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtCardLevel.cy.js
  frontend/cypress/e2e/statusChangeRequest.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementChangesAlert.test.jsx
  frontend/src/components/Agreements/AgreementChangesAlert/AgreementsChangesAlert.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.test.jsx
  frontend/src/components/ChangeRequests/ChangeRequest.hooks.js
  frontend/src/components/ChangeRequests/ChangeRequests.constants.js
  frontend/src/components/ChangeRequests/ChangeRequests.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestList.test.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.test.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
  frontend/src/components/ChangeRequests/index.js
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/components/UI/Modals/ConfirmationModal.jsx
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
Labels: javascript

#2512 feat: ✨ adds Vitest UI
  frontend/bun.lockb
  frontend/package.json
  frontend/vite.config.mjs
Labels: dependencies, javascript

#2522 docs: Update DocumentView propTypes
  frontend/src/components/Agreements/Documents/DocumentView.jsx
Labels: javascript

#2540 chore: Add Cypress plugin configuration
  frontend/eslint.config.js
Labels: javascript

#2533 feat: ✨ adds eslint-plugin-jsx-a11y
  frontend/bun.lockb
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/components/Agreements/AgreementDetails/AgreementHistoryPanel.jsx
  frontend/src/components/Portfolios/ResearchProjects/AdminAndSupportProjectsTable.jsx
  frontend/src/components/Portfolios/ResearchProjects/ResearchProjectsTable.jsx
  frontend/src/components/UI/Footer/NavFooter.jsx
  frontend/src/components/UI/Modals/ConfirmationModal.jsx
  frontend/src/components/UI/Modals/ContainerModal.jsx
  frontend/src/components/UI/PaginationNav/PaginationNav.jsx
  frontend/src/components/UI/Text/TextClip.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/agreements/details/data.js
Labels: dependencies, javascript, a11y

#2516 feat: ✨ round one of Change Requests on Approve page
  backend/ops_api/ops/utils/change_requests.py
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtAgreementLevel.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequests.d.ts
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.test.jsx
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.jsx
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.test.jsx
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/index.js
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/helpers/changeRequests.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/hooks/workflow.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.test.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.constants.js
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/tests/data.js
Labels: javascript

#2547 fix: UX Review fixes
  frontend/src/components/Agreements/AgreementSelect/AgreementSelect.jsx
  frontend/src/components/Agreements/AgreementSelect/AgreementSelect.test.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/UI/Header/Menu.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/index.jsx
Labels: bug, Improvement

#2544 feat: ✨ adds Services Components to approve agreement page
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.test.jsx
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.test.jsx
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.test.jsx
  frontend/src/components/UI/PageHeader/PageHeader.test.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.test.jsx
  frontend/src/pages/agreements/details/Agreement.test.js
Labels: javascript

#2554 fix: 💅 Ops 2349/ux review items
  frontend/src/components/Agreements/AgreementDetails/AgreementHistoryList.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.test.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
Labels: javascript, Improvement

#2552 test: 🧪 application crash when adding BLI to a new Agreement
  frontend/bun.lockb
  frontend/cypress/e2e/createBLIForAgreement.cy.js
Labels: javascript

#2558 feat: ✨ Approve/decline a single agreement round 2
  backend/openapi.yml
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/declineChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/editAgreement.cy.js
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/ChangeRequest.hooks.js
  frontend/src/components/ChangeRequests/ChangeRequests.constants.js
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/TermTag/TermTag.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.test.jsx
Labels: javascript

#2570 feat: ✨ adds confirmation modals, alerts, and notes to Approve Agreement page
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/declineChangeRequestsAtAgreementLevel.cy.js
  frontend/src/components/ChangeRequests/ChangeRequest.hooks.js
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Labels: javascript

#2582 fix: DRAFT BLIs before PATCHing
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/suite.js
  frontend/src/components/ServicesComponents/ServicesComponentForm/suite.js
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/pages/agreements/review/suite.js
Labels: javascript

#2587 feat: ✨ Approver Change Notification icon with CR total
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/src/components/UI/TabsSection/TabsSection.jsx
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/list/AgreementTabs.module.css
  frontend/src/pages/agreements/list/AgreementTabs.test.jsx
  frontend/src/pages/agreements/list/AgreementsTabs.jsx
Labels: javascript

#2586 Adding requisition number and date to BLI
  backend/alembic/versions/2024_07_17_2108-f8ef3a3d90d7_adding_document_table.py
  backend/alembic/versions/2024_07_19_1505-046c78099374_adding_requisition_number_and_.py
  backend/alembic/versions/2024_07_22_1246-479d7630e94c_merge_f8ef3a3d90d7_and_a4a04f1f868e.py
  backend/models/cans.py
Labels: python

#2597 Add flag for BLI that is under current resolution
  backend/alembic/versions/2024_07_19_1650-5438ff1a9b3b_add_flag_for_if_bli_is_under_current_.py
  backend/models/cans.py
Labels: python

#2608 Adding contract_category to the ContractAgreement model
  backend/alembic/versions/2024_07_23_2018-de9beb904925_adding_contract_category.py
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/models/cans.py
Labels: python

#2585 feat: ✨ (4) 2349: Approve Agreement toggle action
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.test.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/Documents/DocumentCollectionView.jsx
  frontend/src/components/Agreements/Documents/styles.module.css
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.helpers.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.test.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.constants.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.scss
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.test.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/index.js
  frontend/src/components/ChangeRequests/ChangeRequests.constants.js
  frontend/src/components/ChangeRequests/ReviewChangeRequestAccordion/ReviewChangeRequestAccordion.jsx
  frontend/src/helpers/changeRequests.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/list/AgreementTabs.module.css
  frontend/src/tests/data.js
Labels: javascript
