Repository HHS/OPRE-OPS, pull requests merged in 2024-11, with the labels that each got.

#2995 feat: ✨ adds filtering of BLIs not-applicable to approver
  frontend/cypress.config.js
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/approveCrossDivisionCRs.cy.js
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementDetailsCards/BLIsByFYSummaryCard/BLIsByFYSummaryCard.jsx
  frontend/src/components/Agreements/AgreementTypes.d.ts
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.helpers.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.test.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLineTypes.d.ts
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.helpers.js
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/UI/Alert/Alert.jsx
  frontend/src/components/UI/Alert/SimpleAlert.jsx
  frontend/src/components/UI/Alert/SimpleAlert.test.jsx
  frontend/src/components/UI/RoundedBox/RoundedBox.jsx
  frontend/src/components/UI/RoundedBox/styles.module.css
  frontend/src/components/UI/TableRowExpandable/TableRowExpandable.jsx
  frontend/src/components/UI/TableTag/TableTag.jsx
  frontend/src/helpers/changeRequests.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/index.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
  frontend/src/tests/data.js
Labels: tech-debt, javascript

#3003 Ops 2810/adr
  .github/workflows/commitlint.yml
  .pre-commit-config.yaml
  commitlint.config.js
  docs/AuthN-diagram.mmd
  docs/BLI-Approval-Sequence.mmd
  docs/BLI/create-bli-step-3.mmd
  docs/HHS-ACF-OPS-Architecture-OPS-app.png
  docs/HHS-ACF-OPS-Architecture-cloud.gov-infra.png
  docs/OPRE-OPS.drawio
  docs/adr/028-semantic-releases.md
  docs/cloud_gov.md
  docs/hhs-ams.json
  docs/models.dot
  docs/models.png
  docs/workflow/Workflow-ClassDiagram-templates.mmd
  docs/workflow/Workflow-ClassDiagram.mmd
  docs/workflow/Workflow-User-Flow.mmd
  docs/workflow/Workflow-db-diagram.mmd
  docs/workflow/Workflow-flowchart-documents.mmd
  docs/workflow/Workflow-flowchart1.mmd
Labels: documentation

#3027 feat: adds CAN detail page
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/components/CANs/CANTypes.d.ts
  frontend/src/components/CANs/CanDetailTabs/CanDetailTabs.jsx
  frontend/src/components/CANs/CanDetailTabs/CanDetailTabs.test.jsx
  frontend/src/components/Portfolios/PortfolioTypes.d.ts
  frontend/src/components/UI/Cards/Card/Card.jsx
  frontend/src/components/UI/Cards/Card/Card.test.jsx
  frontend/src/components/UI/Cards/CurrencyCard/CurrencyCard.jsx
  frontend/src/components/UI/Header/User.jsx
  frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
  frontend/src/components/UI/PageHeader/PageHeader.jsx
  frontend/src/components/UI/RoundedBox/RoundedBox.jsx
  frontend/src/components/UI/Tabs/Tabs.jsx
  frontend/src/components/UI/Tabs/Tabs.module.scss
  frontend/src/components/UI/Tabs/Tabs.test.jsx
  frontend/src/components/UI/Tabs/index.js
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/components/UI/Term/Term.jsx
  frontend/src/components/UI/Term/Term.test.jsx
  frontend/src/components/UI/Term/TermTag.jsx
  frontend/src/components/UI/Term/TermTag.test.jsx
  frontend/src/index.jsx
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanDetail.jsx
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
  frontend/src/pages/cans/detail/getCan.js
  frontend/src/pages/cans/detail/getCan.test.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#3029 feat: ✨adds CAN Spending page BLI Table
  .pre-commit-config.yaml
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/components/CANs/CANBudgetLineTable/CABBudgetLineTable.constants.js
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.test.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.test.jsx
  frontend/src/components/CANs/CANBudgetLineTable/index.js
  frontend/src/index.jsx
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanDetail.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
Labels: javascript

#3051 feat: ✨ adds CAN Cards on Spending Tab
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementTypes.d.ts
  frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/DebugCode/DebugCode.jsx
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/PortfolioFundingByBudgetStatus.jsx
  frontend/src/components/Portfolios/ResearchProjects/ProjectsAndAgreements.jsx
  frontend/src/components/Projects/ProjectTypes.d.ts
  frontend/src/components/UI/Cards/BudgetCard/BigBudgetCard.jsx
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.jsx
  frontend/src/components/UI/Cards/Card/Card.jsx
  frontend/src/components/UI/Cards/DonutGraphWithLegendCard/DonutGraphWithLegendCard.jsx
  frontend/src/components/UI/Cards/DonutGraphWithLegendCard/index.js
  frontend/src/components/UI/Cards/DonutGraphWithLegendCard/styles.module.css
  frontend/src/components/UI/Cards/LineGraphWithLegendCard/LegendItem.jsx
  frontend/src/components/UI/Cards/LineGraphWithLegendCard/LegendItem.test.jsx
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/ProjectAgreementBLICard.jsx
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/index.js
  frontend/src/components/UI/RoundedBox/RoundedBox.jsx
  frontend/src/constants.js
  frontend/src/helpers/utils.js
  frontend/src/pages/Home.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
Labels: javascript

#3078 feat: ✨adds pagination to Can Budget Lines
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx
  frontend/src/components/CANs/CANFundingInfoCard/CANFundingInfoCard.jsx
  frontend/src/components/CANs/CANFundingInfoCard/index.js
  frontend/src/components/CANs/CANTypes.d.ts
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/PortfolioFundingByBudgetStatus.jsx
  frontend/src/components/UI/Cards/BudgetCard/BigBudgetCard.jsx
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.jsx
  frontend/src/components/UI/Cards/Card/Card.jsx
  frontend/src/components/UI/Cards/DonutGraphWithLegendCard/DonutGraphWithLegendCard.jsx
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/ProjectAgreementBLICard.jsx
  frontend/src/components/UI/RoundedBox/RoundedBox.jsx
  frontend/src/components/UI/RoundedBox/styles.module.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanFunding.jsx
Labels: javascript

#3084 feat: ✨adds CAN Funding Cards to CAN Funding page
  frontend/cypress/e2e/canDetail.cy.js
  frontend/sass/uswds/styles.scss
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.helpers.js
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx
  frontend/src/components/CANs/CANBudgetByFYCard/index.js
  frontend/src/components/CANs/CANFundingInfoCard/CANFundingInfoCard.jsx
  frontend/src/components/CANs/CANTable/CANTable.helpers.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.jsx
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.test.jsx
  frontend/src/components/UI/DataViz/LineBar/LineBar.jsx
  frontend/src/components/UI/DataViz/LineBar/LineBar.styles.module.css
  frontend/src/components/UI/DataViz/LineBar/index.js
  frontend/src/constants.js
  frontend/src/pages/cans/detail/Can.helpers.js
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
  frontend/src/uswds/css/styles.css
  frontend/src/uswds/css/styles.css.map
Labels: javascript

#3105 docs: fix CreateUpdateCANFundingBudgetRequest example values
  backend/openapi.yml
Labels: documentation

#3114 refactor: ♻️ use new components
  frontend/src/components/Agreements/AgreementDetailsCards/BLIsByFYSummaryCard/BLIsByFYSummaryCard.jsx
  frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx
  frontend/src/components/UI/DataViz/LineGraph/LineGraph.jsx
Labels: Improvement
