Repository HHS/OPRE-OPS, pull requests merged in 2024-04, with the labels that each got.

#2221 feat: starts onboarding template
  docs/developers/onboarding.md
Labels: documentation

#2235 chore: Update jsx extensions and clean up code
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.jsx
  frontend/src/components/UI/FilterTags/FilterTagsWrapper.jsx
  frontend/src/pages/agreements/CreateEditAgreement.jsx
  frontend/src/pages/agreements/StepCreateAgreement.jsx
  frontend/src/pages/agreements/StepSelectProject.jsx
  frontend/src/pages/budgetLines/BudgetLineContext.hooks.js
  frontend/src/pages/budgetLines/BudgetLineContext.jsx
  frontend/src/pages/budgetLines/CreateBudgetLine.jsx
  frontend/src/pages/budgetLines/StepSelectProjectAndAgreement.jsx
  frontend/src/pages/budgetLines/index.jsx
Labels: javascript

#2240 fix: need runtime dependency of express
  frontend/Dockerfile.azure
Labels: dependencies

#2231 feat: ✨SC Form to use DateRangePicker
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/cypress/e2e/components.cy.js
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/ServicesComponents/ContractTypeSelect/ContractTypeSelect.jsx
  frontend/src/components/ServicesComponents/ServiceReqTypeSelect/ServiceReqTypeSelect.jsx
  frontend/src/components/ServicesComponents/ServicesComponentAccordion/ServicesComponentAccordion.jsx
  frontend/src/components/ServicesComponents/ServicesComponentForm/ServicesComponentForm.jsx
  frontend/src/components/ServicesComponents/ServicesComponentMetadata/ServicesComponentMetadata.jsx
  frontend/src/components/ServicesComponents/ServicesComponents.constants.js
  frontend/src/components/ServicesComponents/ServicesComponents.helpers.js
  frontend/src/components/ServicesComponents/ServicesComponents.hooks.js
  frontend/src/components/ServicesComponents/ServicesComponents.jsx
  frontend/src/components/UI/Form/TextArea/TextArea.jsx
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.jsx
  frontend/src/components/UI/USWDS/DateRangePickerWrapper/DateRangePickerWrapper.jsx
  frontend/src/helpers/utils.js
  frontend/src/index.jsx
  frontend/src/pages/DateRangePickerPage.jsx
Labels: javascript
