Repository HHS/OPRE-OPS, pull requests merged in 2024-08, with the labels that each got.

#2625 (5) feat: CanReviewAccordion improvements on Agreement Approve page
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtCardLevel.cy.js
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.test.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.constants.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.helpers.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.constants.js
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffTable.test.js
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewTable.constants.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.constants.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/CANs/CANFundingCard/CanFundingCard.test.jsx
  frontend/src/components/ChangeRequests/BudgetChangeReviewCard/BudgetChangeReviewCard.test.jsx
  frontend/src/components/UI/Form/DesiredAwardDate/DesiredAwardDate.jsx
  frontend/src/components/UI/Form/DesiredAwardDate/DesiredAwardDate.test.js
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/hooks/useChangeRequests.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Labels: javascript

#2643 refactor: Update success Alert for Budget Changes
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/details/AgreementDetails.test.js
Labels: javascript

#2646 feat: 💅 Review Page improvements
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/cypress/e2e/statusChangeRequest.cy.js
  frontend/src/components/Agreements/AgreementActionAccordion/AgreementActionAccordion.jsx
  frontend/src/components/Agreements/AgreementActionAccordion/AgreementActionAccordion.test.jsx
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementChangesAccordion/AgreementChangesAccordion.jsx
  frontend/src/components/Agreements/AgreementChangesAccordion/index.js
  frontend/src/components/Agreements/AgreementChangesAccordion/small-summary-card.module.css
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditFormSuite.js
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.test.jsx
  frontend/src/components/Agreements/ProjectOfficerComboBox.jsx
  frontend/src/components/Agreements/TeamMemberComboBox.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewTable.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestList.test.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.jsx
  frontend/src/components/ChangeRequests/StatusChangeReviewCard/StatusChangeReviewCard.test.jsx
  frontend/src/components/ServicesComponents/ContractTypeSelect/ContractTypeSelect.jsx
  frontend/src/components/UI/RadioButtonTile/RadioButtonTile.jsx
  frontend/src/helpers/utils.js
  frontend/src/hooks/agreement.hooks.js
  frontend/src/pages/agreements/review/ReviewAgreement.constants.js
  frontend/src/pages/agreements/review/ReviewAgreement.hooks.js
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/pages/agreements/review/reviewAgreement.hooks.js
  frontend/src/pages/agreements/review/suite.js
Labels: javascript

#2639 Show Approval/Denial notifications for an Agreement
  backend/models/cans.py
  backend/ops_api/ops/utils/budget_line_items.py
  backend/ops_api/ops/utils/change_requests.py
  backend/ops_api/tests/ops/features/test_edit_agreement_metadata.py
  frontend/cypress/e2e/reviewChangeRequestResponse.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.jsx
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.test.jsx
  frontend/src/components/Agreements/AgreementChangesResponseAlert/index.js
  frontend/src/pages/agreements/details/Agreement.jsx
Labels: python, javascript

#2681 feat: ✨adds CR Budget Change messages to Alert
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/cypress/e2e/reviewChangeRequestResponse.cy.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/ServicesComponents/ServicesComponents.hooks.js
  frontend/src/components/ServicesComponents/ServicesComponents.jsx
Labels: javascript

#2685 refactor: updating unit-tests
  frontend/cypress/e2e/components.cy.js
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.test.jsx
  frontend/src/components/UI/USWDS/DateRangePickerWrapper/DateRangePickerMock.js
  frontend/src/components/UI/USWDS/DateRangePickerWrapper/DateRangePickerWrapper.jsx
  frontend/src/components/UI/USWDS/DateRangePickerWrapper/DateRangePickerWrapper.test.jsx
Labels: javascript

#2700 fix: checks user permission to show forms
  frontend/src/components/Agreements/AgreementDetailsCards/BLIsByFYSummaryCard/BLIsByFYSummaryCard.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/CANs/CanCard/CanCard.jsx
  frontend/src/components/CANs/CanCard/CanCard.skip.js
  frontend/src/components/CANs/CanCard/CanCard.test.jsx
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.jsx
  frontend/src/components/UI/USWDS/DateRangePickerWrapper/DateRangePickerWrapper.jsx
  frontend/src/helpers/utils.js
Labels: javascript

#2727 fix: adds default to GCS
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
  frontend/src/pages/agreements/list/AgreementsFilterButton.jsx
Labels: javascript

#2730 updating OWASP ZAP DAST scans to use our new staging environment URL
  .github/workflows/nightly_scans.yml
Labels: security-privacy-compliance

#2732 refactor: 💀kill bli workflow
  frontend/cypress/e2e/cancelBudgetLine.cy.js
  frontend/cypress/e2e/createBudgetLine.cy.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/UI/Header/Menu.jsx
  frontend/src/index.jsx
  frontend/src/pages/budgetLines/BudgetLineContext.hooks.js
  frontend/src/pages/budgetLines/BudgetLineContext.jsx
  frontend/src/pages/budgetLines/CreateBudgetLine.jsx
  frontend/src/pages/budgetLines/CreateBudgetLineFlow.jsx
  frontend/src/pages/budgetLines/CreateBudgetLineFlow.test.js
  frontend/src/pages/budgetLines/StepSelectProjectAndAgreement.jsx
  frontend/src/pages/budgetLines/index.jsx
Labels: javascript

#2734 refactor: ♻️ updates logic for disabled icons text
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/ChangeIcons/ChangeIcons.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/hooks/budget-line.hooks.js
  frontend/src/pages/budgetLines/list/BudgetLinesItems.hooks.js
Labels: don't merge, javascript
