Repository HHS/OPRE-OPS, pull requests merged in 2025-08, with the labels that each got.

#4182 feat: add project title to budget line item export
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Labels: story

#4234 test: 🧪 adds test for proc shop w draft blis
  frontend/cypress/e2e/procurementShopChangeRequest.cy.js
Labels: task

#4235 OPS-4205: CANs filter bug fix
  backend/data_tools/data/can_data.json5
  backend/models/cans.py
  backend/ops_api/ops/services/cans.py
  backend/ops_api/tests/ops/can/test_can.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANFundingInfoCard/CANFundingInfoCard.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.helpers.js
  frontend/src/components/CANs/CANTable/CANTableRow.helpers.test.js
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: bug-medium

#4261 Remove deps and refactor
  backend/ops_api/Pipfile
  backend/ops_api/Pipfile.lock
  backend/ops_api/ops/resources/cans.py
  backend/ops_api/ops/resources/notifications.py
  backend/ops_api/ops/resources/research_project_funding_summary.py
  backend/ops_api/ops/utils/research_project_helper.py
  backend/ops_api/tests/ops/funding_summary/test_research_project_funding_summary.py
  backend/ops_api/tests/ops/notification/test_notification.py
Labels: dependencies

#4265 feat: super user can edit amount on contract agreement
  frontend/cypress/e2e/editBudgetLineByPowerUser.cy.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.test.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIAndSCs.test.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/CANs/CanComboBox/CanComboBox.jsx
  frontend/src/components/CANs/CanComboBox/CanComboBox.test.js
  frontend/src/components/UI/Form/ComboBox/ComboBox.jsx
  frontend/src/components/UI/Form/ComboBox/ComboBox.test.js
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.jsx
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.test.jsx
  frontend/src/components/Users/UserInfo/UserInfo.jsx
Labels: javascript, a11y

#4258 docs: 📚 add comprehensive guide for creating new users in OPS
  docs/developers/creating-new-users.md
Labels: documentation
