Repository HHS/OPRE-OPS, pull requests merged in 2025-04, with the labels that each got.

#3600 OPS-3323 COR
  backend/alembic/versions/2025_03_20_1707-f8b2a2a8b484_added_alternate_cor_project_officer_to_.py
  backend/alembic/versions/2025_03_26_1814-9b0942c494df_.py
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/data_tools/data/first_contract_data.json5
  backend/models/agreements.py
  backend/openapi.yml
  backend/ops_api/ops/resources/agreements.py
  backend/ops_api/ops/resources/budget_line_items.py
  backend/ops_api/ops/resources/procurement_steps.py
  backend/ops_api/ops/schemas/agreements.py
  backend/ops_api/tests/conftest.py
  backend/ops_api/tests/ops/agreement/test_agreement.py
  frontend/cypress/e2e/agreementDelete.cy.js
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/cypress/e2e/agreementDetailsEdit.cy.js
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/src/components/Agreements/AgreementDetails/AgreementHistoryList.jsx
  frontend/src/components/Agreements/AgreementDetails/AgreementHistoryPanel.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.jsx
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
  frontend/src/components/Agreements/AgreementTypes.d.ts
  frontend/src/components/Agreements/ProjectOfficerComboBox.jsx
  frontend/src/components/Agreements/TeamMemberComboBox.jsx
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/helpers/utils.js
  frontend/src/hooks/agreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetails.test.js
  frontend/src/pages/agreements/details/AgreementDetailsEdit.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.hooks.js
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/tests/data.js
Labels: released

#3670 fix: update ux and bugs for video creation
  frontend/cypress/e2e/createResearchProject.cy.js
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/Portfolios/PortfolioBudgetSummary/PortfolioBudgetSummary.jsx
  frontend/src/components/UI/Cards/BudgetCard/BudgetCard.jsx
  frontend/src/pages/agreements/CreateEditAgreement.jsx
  frontend/src/pages/projects/CreateProject.jsx
  frontend/src/pages/projects/suite.js
Labels: javascript

#3671 refactor: simplify review agreement validation
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
Labels: javascript

#3656 fix: removes unwanted margin
  frontend/cypress/e2e/agreementList.cy.js
  frontend/src/components/UI/Alert/SlimAlert.jsx
Labels: design

#3661 feat: agreement list improvements
  backend/alembic/versions/2025_03_20_1707-f8b2a2a8b484_added_alternate_cor_project_officer_to_.py
  backend/alembic/versions/2025_03_24_1509-486929593d89_remove_payee_from_direct_agreement.py
  backend/alembic/versions/2025_03_26_1814-9b0942c494df_.py
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/models/budget_line_items.py
  backend/ops_api/Pipfile
  backend/ops_api/Pipfile.lock
  backend/ops_api/ops/__init__.py
  backend/ops_api/ops/resources/agreements.py
  backend/ops_api/ops/resources/agreements_constants.py
  backend/ops_api/ops/resources/cans.py
  backend/ops_api/ops/schemas/agreements.py
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/tests/ops/agreement/test_agreement.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
  backend/ops_api/tests/ops/can/test_can.py
  backend/ops_api/tests/ops/can/test_portfolio_cans.py
  backend/ops_api/tests/ops/features/test_edit_agreement_metadata.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  backend/ops_api/tests/ops/funding_summary/test_portfolio_funding_summary.py
  backend/ops_api/tests/ops/research_project/test_research_project.py
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/cypress/e2e/agreementList.cy.js
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/canList.cy.js
  frontend/cypress/e2e/editAgreement.cy.js
  frontend/cypress/e2e/editAgreementAsBasicUser.cy.js
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/api/opsAPI.test.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.test.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.helpers.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.jsx
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.test.js
  frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
  frontend/src/pages/cans/detail/CanDetail.jsx
Labels: bug-high

#3680 fix: corrects Alerts for the CAN Funding page
  frontend/src/pages/cans/detail/CanFunding.hooks.js
Labels: design

#3681 Update permission type on deleting service components
  backend/ops_api/ops/resources/services_component.py
  backend/ops_api/tests/auth_client.py
  backend/ops_api/tests/conftest.py
  backend/ops_api/tests/ops/can/test_services_component.py
Labels: bug-high

#3684 Updates to help center
  frontend/src/pages/help/FAQ.jsx
  frontend/src/pages/help/FAQ.test.jsx
  frontend/src/pages/help/Glossary.jsx
  frontend/src/pages/help/HowToGuides.jsx
  frontend/src/pages/help/HowToGuides.test.jsx
Labels: documentation

#3688 refactor: enhance All Budget Items List
  backend/models/budget_line_items.py
  backend/ops_api/ops/resources/budget_line_items.py
  backend/ops_api/ops/schemas/budget_line_items.py
  backend/ops_api/ops/schemas/can_history.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementBudgetLinesHeader.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.hooks.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.test.jsx
  frontend/src/components/BudgetLineItems/BLIStatusSummaryCard/BLIStatusSummaryCard.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTotalSummaryCard/BudgetLinesTotalSummaryCard.jsx
  frontend/src/components/BudgetLineItems/SummaryCardsSection/SummaryCardsSection.jsx
  frontend/src/components/UI/PaginationNav/PaginationNav.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
  frontend/src/pages/budgetLines/list/BudgetLinesItems.hooks.js
Labels: bug-high

#3705 fix: proc shop to AllBLIRow
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.test.jsx
Labels: bug-low

#3683 fix: approve agreement with planned and draft budget lines
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.jsx
  frontend/src/components/Agreements/AgreementBLIAccordion/AgreementBLIAccordion.test.jsx
  frontend/src/components/Agreements/AgreementDetailsCards/AgreementTotalCard/AgreementTotalCard.jsx
  frontend/src/helpers/agreement.helpers.js
  frontend/src/helpers/agreement.helpers.test.js
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/tests/data.js
Labels: bug-high

#3714 refactor: update PortfolioList component
  frontend/cypress/e2e/portfolioList.cy.js
  frontend/src/pages/portfolios/list/PortfolioList.jsx
  frontend/src/pages/portfolios/list/getPortfolioList.js
  frontend/src/pages/portfolios/list/getPortfolioList.test.js
  frontend/src/pages/portfolios/list/portfolioListSlice.js
  frontend/src/store.js
Labels: javascript

#3728 feat: enhances export ux
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Labels: bug-high

#3729 feat: integrate rehype-raw for enhanced Markdown
  frontend/bun.lockb
  frontend/package.json
  frontend/src/pages/help/FAQ.jsx
  frontend/src/pages/help/Feedback.jsx
  frontend/src/pages/help/Glossary.jsx
  frontend/src/pages/help/HelpCenter.jsx
  frontend/src/pages/help/HowToGuides.jsx
Labels: javascript

#3743 fix: refine improve agreement filtering in PortfolioSpending
  frontend/src/components/Agreements/DetailsTabs/DetailsTabs.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.helpers.js
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.helpers.test.js
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
Labels: bug-medium

#3747 fix: banner not showing up for non-contract agreement in prod
  frontend/src/helpers/agreement.helpers.js
Labels: bug-high

#3748 feat: adds Agreement link and conditionally renders Portfolio url
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.test.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.test.jsx
  frontend/src/components/UI/HeroDescription/HeroDescription.jsx
Labels: bug-low

#3757 Hotfix/dday 2 fixes
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/ops_api/ops/resources/budget_line_items.py
  backend/ops_api/ops/services/agreements.py
  backend/ops_api/ops/services/ops_service.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
  backend/ops_api/tests/ops/can/test_portfolio_cans.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLineTypes.d.ts
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.helpers.js
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.helpers.test.js
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
  frontend/src/components/UI/Table/Table.jsx
  frontend/src/constants.js
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/budgetLines.helpers.test.js
  frontend/src/helpers/utils.js
  frontend/src/pages/cans/detail/Can.hooks.js
Labels: bug-high

#3774 refactor: ♻️ BLI Form to use line_description
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/createBLIsAndSCs.constants.js
Labels: javascript

#3769 Enhance refresh in rtkq
  backend/ops_api/ops/auth/service.py
  frontend/src/api/opsAPI.js
  frontend/src/api/opsAuthAPI.js
  frontend/src/api/postRefresh.js
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/components/Auth/auth.js
  frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
  frontend/src/errorMiddleware.js
  frontend/src/errorMiddleware.test.js
  frontend/src/hooks/useNotifications.js
  frontend/src/store.js
Labels: bug-medium

#3732 refactor: ♻️ use agreement meta isEditable in place of FE logic
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/cypress/e2e/editAgreement.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementMetaAccordion/AgreementMetaAccordion.jsx
  frontend/src/components/Agreements/AgreementTypes.d.ts
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.test.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.helpers.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.test.js
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewTable.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/hooks/agreement.hooks.js
  frontend/src/pages/agreements/EditAgreement.jsx
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetails.test.js
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.hooks.js
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
Labels: javascript

#3790 refactor: allow agreement editing while budgetline is in review
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/budgetLines.helpers.test.js
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetails.test.js
  frontend/src/pages/agreements/review/ReviewAgreement.helpers.js
  frontend/src/pages/agreements/review/ReviewAgreement.helpers.test.js
Labels: bug-medium

#3776 feat(portfolio-funding): display active CANs in descending order by appropriation year
  backend/data_tools/data/can_data.json5
  backend/ops_api/ops/resources/portfolio_cans.py
  backend/ops_api/tests/ops/can/test_can.py
  backend/ops_api/tests/ops/can/test_can_funding_budget.py
  backend/ops_api/tests/ops/can/test_portfolio_cans.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/canList.cy.js
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Labels: bug-high

#3802 fix: 🐛 Agreement List edit button logic
  frontend/cypress/e2e/agreementList.cy.js
  frontend/cypress/e2e/budgetChangeRequest.cy.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
Labels: bug-medium

#3807 fix: update agreement type label to AA for non contract agreement
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/helpers/agreement.helpers.js
  frontend/src/pages/agreements/details/AgreementDetails.test.js
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
Labels: javascript, bug-medium

#3818 refactor: button styles globally
  frontend/sass/uswds/styles.scss
  frontend/src/components/UI/HeroDescription/HeroDescription.jsx
  frontend/src/components/UI/HeroDescription/HeroDescription.module.css
  frontend/src/uswds/css/styles.css
  frontend/src/uswds/css/styles.css.map
Labels: bug-low

#3819 docs: update faq.jsx
  frontend/src/pages/help/FAQ.jsx
Labels: documentation

#3820 feat: update agreement edit logic on agreement list
  backend/ops_api/ops/resources/agreements.py
  frontend/cypress/e2e/agreementList.cy.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.helpers.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
Labels: tech-debt

#3822 fix: add calculation for received percentage and update graph data
  frontend/src/components/UI/Cards/BudgetCard/ReceivedFundingCard.jsx
  frontend/src/components/UI/Cards/BudgetCard/ReceivedFundingCard.test.jsx
  frontend/src/components/UI/DataViz/LineGraph/ReverseLineGraph.jsx
Labels: bug-medium
