Repository HHS/OPRE-OPS, pull requests merged in 2025-02, with the labels that each got.

#3400 chore: removed feature flag from cans
  frontend/src/index.jsx
  frontend/src/pages/cans/list/CanList.jsx
Labels: javascript

#3399 fix: fix permission to view page using state
  frontend/src/pages/agreements/approve/ApproveAgreement.hooks.js
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
Labels: bug

#3425 fix: fixed can list render bug
  backend/data_tools/data/can_data.json5
  backend/ops_api/tests/ops/can/test_can.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/Dockerfile
  frontend/cypress/e2e/canList.cy.js
  frontend/src/constants.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: bug, bug-high

#3419 style: remove unused FY column from CAN Table
  frontend/src/components/CANs/CANTable/CANTable.test.jsx
  frontend/src/components/CANs/CANTable/CANTableHead.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.test.jsx
Labels: UX task

#3413 feat: adds Help Center
  frontend/Dockerfile
  frontend/bun.lockb
  frontend/cypress.config.js
  frontend/cypress/e2e/helpCenter.cy.js
  frontend/cypress/support/e2e.js
  frontend/package.json
  frontend/src/components/UI/Accordion/Accordion.jsx
  frontend/src/components/UI/Header/Menu.jsx
  frontend/src/index.jsx
  frontend/src/pages/help/FAQ.jsx
  frontend/src/pages/help/FAQ.test.jsx
  frontend/src/pages/help/Feedback.jsx
  frontend/src/pages/help/Feedback.test.jsx
  frontend/src/pages/help/Glossary.jsx
  frontend/src/pages/help/Glossary.test.jsx
  frontend/src/pages/help/HelpCenter.jsx
  frontend/src/pages/help/UserGuides.jsx
  frontend/src/pages/help/UserGuides.test.jsx
Labels: documentation, javascript

#3435 feat: updates bun docker config and tweaks to dev scrip
  docker-compose.yml
  frontend/Dockerfile
  frontend/package.json
Labels: infrastructure

#3451 fix: bug in reset api; improve NotificationCenter.jsx
  frontend/src/api/opsAPI.js
  frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
  frontend/src/errorMiddleware.js
  frontend/src/errorMiddleware.test.js
Labels: bug

#3453 fix: fixed hmr
  frontend/Dockerfile
Labels: bug

#3474 fix: correct type on funding received response
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/tests/ops/can/test_can_funding_received.py
Labels: bug

#3468 fix: fixes CANList and CANTable mismatch bug
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
Labels: bug-high

#3471 Ops 3465/input bug
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/tests/ops/can/test_can_funding_budget.py
  backend/ops_api/tests/ops/can/test_can_funding_received.py
  backend/ops_api/tests/ops/can_history/test_can_history.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.test.jsx
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanFundingSuite.js
  frontend/src/pages/cans/list/CANFilterButton/CANFilterButton.hooks.js
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.hooks.js
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.jsx
  frontend/src/pages/cans/list/CanList.jsx
Labels: bug

#3454 feat: updates Portfolio details
  backend/ops_api/ops/resources/administrative_and_support_projects.py
  backend/ops_api/ops/resources/research_projects.py
  docker-compose.yml
  frontend/cypress/e2e/canList.cy.js
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/cypress/e2e/portfolioList.cy.js
  frontend/sass/uswds/styles.scss
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CABBudgetLineTable.constants.js
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/CANs/CANBudgetSummary/CANBudgetSummary.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTableRow.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/CANs/CanCard/CanCard.jsx
  frontend/src/components/CANs/CanCard/CanCard.test.jsx
  frontend/src/components/CANs/CanCard/styles.module.css
  frontend/src/components/Portfolios/BudgetAndFunding/BudgetAndFunding.jsx
  frontend/src/components/Portfolios/BudgetAndFunding/BudgetAndFunding.module.css
  frontend/src/components/Portfolios/BudgetAndSpending/BudgetAndSpending.jsx
  frontend/src/components/Portfolios/BudgetAndSpending/BudgetAndSpending.skip.js
  frontend/src/components/Portfolios/Funding/AdminAndSupportProjectsTable.jsx
  frontend/src/components/Portfolios/Funding/AdminAndSupportProjectsTable.test.js
  frontend/src/components/Portfolios/Funding/PortfolioFunding.jsx
  frontend/src/components/Portfolios/Funding/ProjectsAndAgreements.jsx
  frontend/src/components/Portfolios/Funding/ProjectsAndAgreements.test.js
  frontend/src/components/Portfolios/Funding/ResearchBudgetVsSpending.jsx
  frontend/src/components/Portfolios/Funding/ResearchBudgetVsSpending.test.js
  frontend/src/components/Portfolios/Funding/ResearchProjectFundingSlice.js
  frontend/src/components/Portfolios/Funding/ResearchProjects.module.css
  frontend/src/components/Portfolios/Funding/ResearchProjects.skip.js
  frontend/src/components/Portfolios/Funding/ResearchProjectsTable.jsx
  frontend/src/components/Portfolios/Funding/ResearchProjectsTable.test.js
  frontend/src/components/Portfolios/Funding/data.js
  frontend/src/components/Portfolios/Funding/getResearchProjectsFunding.js
  frontend/src/components/Portfolios/Funding/tables.scss
  frontend/src/components/Portfolios/PortfolioBudgetSummary/PortfolioBudgetSummary.jsx
  frontend/src/components/Portfolios/PortfolioTabsSection/PortfolioTabsSection.jsx
  frontend/src/components/Portfolios/ResearchProjects/ResearchProjects.jsx
  frontend/src/components/UI/Cards/Card/Card.jsx
  frontend/src/components/UI/Cards/LineGraphWithLegendCard/LegendItem.jsx
  frontend/src/components/UI/Form/CurrencyInput/CurrencyInput.jsx
  frontend/src/components/UI/Header/Menu.jsx
  frontend/src/components/UI/Hero/Hero.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/index.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.module.css
  frontend/src/store.js
  frontend/src/uswds/css/styles.css
  frontend/src/uswds/css/styles.css.map
Labels: javascript

#3518 chore: update Vite dev server configuration
  frontend/vite.config.mjs
Labels: infrastructure

#3526 fix: ux review improvements on portfolios
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.helpers.js
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.helpers.test.js
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/CANs/CanCard/CanCard.jsx
  frontend/src/components/CANs/CanCard/CanCard.test.jsx
  frontend/src/components/CANs/CanCard/styles.module.css
  frontend/src/components/Portfolios/Funding/PortfolioFunding.jsx
  frontend/src/components/Portfolios/PortfolioBudgetSummary/index.js
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.skip.js
  frontend/src/components/Portfolios/PortfolioSpending/index.js
  frontend/src/components/UI/Cards/DonutGraphWithLegendCard/DonutGraphWithLegendCard.jsx
  frontend/src/components/UI/Cards/LineGraphWithLegendCard/LegendItem.jsx
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/ProjectAgreementBLICard.jsx
  frontend/src/components/UI/Tag/Tag.jsx
  frontend/src/components/UI/Text/TextClip.jsx
  frontend/src/index.jsx
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Labels: javascript

#3532 chore: cleanup unused Portfolio code
  frontend/src/components/Portfolios/Funding/AdminAndSupportProjectsTable.jsx
  frontend/src/components/Portfolios/Funding/AdminAndSupportProjectsTable.test.js
  frontend/src/components/Portfolios/Funding/ProjectsAndAgreements.jsx
  frontend/src/components/Portfolios/Funding/ProjectsAndAgreements.test.js
  frontend/src/components/Portfolios/Funding/ResearchBudgetVsSpending.jsx
  frontend/src/components/Portfolios/Funding/ResearchBudgetVsSpending.test.js
  frontend/src/components/Portfolios/Funding/ResearchProjectFundingSlice.js
  frontend/src/components/Portfolios/Funding/ResearchProjects.module.css
  frontend/src/components/Portfolios/Funding/ResearchProjects.skip.js
  frontend/src/components/Portfolios/Funding/ResearchProjectsTable.jsx
  frontend/src/components/Portfolios/Funding/ResearchProjectsTable.test.js
  frontend/src/components/Portfolios/Funding/data.js
  frontend/src/components/Portfolios/Funding/getResearchProjectsFunding.js
  frontend/src/components/Portfolios/Funding/tables.scss
  frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.jsx
  frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.module.css
  frontend/src/components/Portfolios/PeopleAndTeams/PeopleAndTeams.skip.js
  frontend/src/components/Portfolios/PortfolioBudgetSummary/portfolioBudgetSummarySlice.js
  frontend/src/components/Portfolios/PortfolioBudgetSummary/util.js
  frontend/src/components/Portfolios/PortfolioBudgetSummary/util.test.js
  frontend/src/components/Portfolios/PortfolioFunding/PortfolioFunding.jsx
  frontend/src/components/Portfolios/PortfolioFunding/index.js
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/PortfolioFundingByBudgetStatus.jsx
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/styles.module.css
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/util.js
  frontend/src/components/Portfolios/PortfolioFundingByBudgetStatus/util.test.js
  frontend/src/components/Portfolios/PortfolioHeader/PortfolioHeader.jsx
  frontend/src/components/Portfolios/PortfolioHeader/PortfolioHeader.test.js
  frontend/src/components/Portfolios/PortfolioHeader/styles.module.css
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioCarryForwardFunding.jsx
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioCarryForwardFunding.test.js
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioFundingTotal.jsx
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioFundingTotal.test.js
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioNewFunding.jsx
  frontend/src/components/Portfolios/PortfolioSummaryCards/PortfolioNewFunding.test.js
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/ProjectAgreementBLICard.jsx
  frontend/src/components/UI/FiscalYear/FiscalYear.jsx
  frontend/src/index.jsx
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/list/CANFiscalYearSelect/CANFiscalYearSelect.jsx
  frontend/src/pages/cans/list/CanList.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
  frontend/src/pages/portfolios/detail/getPortfolio.js
  frontend/src/pages/portfolios/detail/getPortfolio.test.js
  frontend/src/pages/portfolios/detail/getResearchProjects.js
  frontend/src/pages/portfolios/detail/getResearchProjects.test.js
  frontend/src/pages/portfolios/detail/portfolioSlice.js
  frontend/src/pages/portfolios/detail/portfolioSlice.test.js
  frontend/src/store.js
Labels: tech-debt

#3538 refactor: updates data for cards
  frontend/src/components/Portfolios/PortfolioBudgetSummary/PortfolioBudgetSummary.jsx
  frontend/src/components/Portfolios/PortfolioFunding/PortfolioFunding.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Labels: javascript

#3540 fix: fixed can list table pagination bug
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
Labels: bug

#3502 chore: document portfolio funding summary endpoint
  backend/openapi.yml
  backend/ops_api/ops/resources/portfolio_funding_summary.py
  backend/ops_api/ops/schemas/portfolio_funding_summary.py
  backend/ops_api/ops/utils/portfolios.py
Labels: documentation, tech-debt

#3537 Bug Fix: Add Format Check for "Obligate by Date" in the Add Budget Line Form
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.test.js
  frontend/src/components/Agreements/AgreementsTable/AgreementsTable.test.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/datePickerSuite.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/UI/Form/IsRequiredHelper/IsRequiredHelper.jsx
  frontend/src/components/UI/Text/TextClip.jsx
  frontend/src/components/UI/USWDS/DatePicker/DatePicker.jsx
  frontend/src/pages/agreements/details/Agreement.jsx
Labels: bug
