Repository HHS/OPRE-OPS, pull requests merged in 2025-05, with the labels that each got.

#3838 feat: add tooltips for budget line edit restrictions based on status
  frontend/cypress/e2e/agreementDelete.cy.js
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.test.jsx
  frontend/src/components/BudgetLineItems/ChangeIcons/ChangeIcons.jsx
  frontend/src/components/BudgetLineItems/ChangeIcons/ChangeIcons.test.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/budgetLines.helpers.test.js
Labels: UX task

#3827 Ops 3779/bli status bug
  backend/ops_api/ops/resources/agreements.py
Labels: python, bug-high

#3858 feat(security): hides leaky web server info
  frontend/nginx.conf
Labels: security-privacy-compliance

#3843 fix: adds new budget-lines filter endpoint
  backend/openapi.yml
  backend/ops_api/ops/resources/budget_line_items.py
  backend/ops_api/ops/schemas/budget_line_items.py
  backend/ops_api/ops/services/budget_line_items.py
  backend/ops_api/ops/urls.py
  backend/ops_api/ops/views.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/BLIStatusComboBox/BLIStatusComboBox.jsx
  frontend/src/components/BudgetLineItems/BudgetLineTypes.d.ts
  frontend/src/components/BudgetLineItems/SummaryCardsSection/SummaryCardsSection.jsx
  frontend/src/components/Portfolios/PortfoliosComboBox/PortfoliosComboBox.jsx
  frontend/src/components/Portfolios/PortfoliosComboBox/PortfoliosComboBox.test.js
  frontend/src/components/UI/FilterButton/FilterButton.jsx
  frontend/src/helpers/tableExport.helpers.js
  frontend/src/pages/budgetLines/list/BLIFilterButton.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Labels: bug-medium

#3860 test: improve perf on components test
  frontend/cypress/e2e/components.cy.js
Labels: tech-debt

#3864 feat: ✨ App-wide scroll to top
  frontend/src/App.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/components/CANs/CANDetailForm/CANDetailForm.hooks.js
  frontend/src/components/CANs/CANDetailForm/CANDetailForm.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTableRow.jsx
  frontend/src/helpers/scrollToTop.helper.js
  frontend/src/hooks/useScrollToTop.js
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
Labels: UX task

#3861 refactor: integrate external data sources for Help Center
  frontend/src/pages/help/FAQ.jsx
  frontend/src/pages/help/Glossary.jsx
  frontend/src/pages/help/HowToGuides.jsx
  frontend/src/pages/help/content/faq.js
  frontend/src/pages/help/content/glossary.js
  frontend/src/pages/help/content/howToGuides.js
Labels: documentation

#3857 chore: update react-markdown to version 10.1.0 and refactor LogItem c…
  frontend/bun.lockb
  frontend/package.json
  frontend/src/components/UI/LogItem/LogItem.jsx
  frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
Labels: dependencies

#3856 ZAP/DAST improvements
  .github/actions/zap-json-to-sarif/zap_json_to_sarif.py
  .github/workflows/nightly_scans.yml
Labels: security-privacy-compliance

#3867 OPS-3786: allow DDs and Team Leaders in agreements onlyMy filter
  backend/openapi.yml
  backend/ops_api/ops/resources/agreements.py
  backend/ops_api/ops/schemas/agreements.py
  backend/ops_api/tests/ops/agreement/test_agreement.py
  frontend/cypress/e2e/agreementList.cy.js
  frontend/src/pages/agreements/list/AgreementsList.jsx
Labels: task

#3884 fix: 👾 enhances delete Services Components functionality
  frontend/cypress/e2e/agreementDetailsEdit.cy.js
  frontend/cypress/e2e/utils.js
  frontend/src/components/ServicesComponents/ServicesComponentForm/ServicesComponentForm.jsx
  frontend/src/components/ServicesComponents/ServicesComponents.constants.js
  frontend/src/components/ServicesComponents/ServicesComponents.hooks.js
  frontend/src/components/ServicesComponents/ServicesComponents.jsx
  frontend/src/components/ServicesComponents/ServicesComponentsList/ServicesComponentsList.jsx
Labels: bug-low

#3899 OPS-3881: CANs mismatch on portfolio and can list
  frontend/cypress/e2e/canList.cy.js
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: bug-medium

#3894 feat: ✨ adds more Service Components
  frontend/src/components/ServicesComponents/ServicesComponentForm/ServicesComponentForm.jsx
  frontend/src/components/ServicesComponents/ServicesComponentSelect/ServicesComponentSelect.jsx
  frontend/src/components/ServicesComponents/ServicesComponents.constants.js
  frontend/src/components/UI/Form/Select/Select.jsx
  frontend/src/components/UI/Form/Select/Select.test.jsx
Labels: OPS-support

#3912 fix: fix budget lines list error when BLI has no amount
  backend/ops_api/ops/services/budget_line_items.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
Labels: bug-high

#3903 feat: adds sort to team members of an Agreement
  frontend/cypress/e2e/agreementList.cy.js
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/ProjectOfficerComboBox.jsx
  frontend/src/components/Agreements/TeamMemberComboBox.jsx
  frontend/src/components/Agreements/TeamMemberList.jsx
  frontend/src/components/UI/Form/ComboBox/ComboBox.hooks.js
  frontend/src/components/UI/Form/ComboBox/ComboBox.jsx
  frontend/src/components/UI/Form/FiscalYearComboBox/FiscalYearComboBox.jsx
  frontend/src/components/UI/Form/FiscalYearComboBox/FiscalYearComboBox.test.js
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
Labels: OPS-support

#3907 refactor: improve validation logic and reset handling
  frontend/cypress/e2e/createAgreementWithValidations.cy.js
  frontend/src/components/BudgetLineItems/BudgetLinesForm/BudgetLinesForm.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesForm/datePickerSuite.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.hooks.js
  frontend/src/components/BudgetLineItems/CreateBLIsAndSCs/CreateBLIsAndSCs.jsx
Labels: bug-high, OPS-support

#3913 refactor: ♻️ replace error messages with ErrorPage
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/Agreements/AgreementCANReviewAccordion/AgreementCANReviewAccordion.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementReasonSelect.jsx
  frontend/src/components/Agreements/AgreementTypeSelect.jsx
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.test.js
  frontend/src/components/Agreements/ProcurementShopSelectWithFee/ProcurementShopSelectWithFee.test.js
  frontend/src/components/Agreements/ProjectOfficerComboBox.jsx
  frontend/src/components/Agreements/TeamMemberComboBox.jsx
  frontend/src/components/CANs/CANFundingCard/CANFundingCard.jsx
  frontend/src/components/CANs/CanComboBox/CanComboBox.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/Portfolios/PortfoliosComboBox/PortfoliosComboBox.jsx
  frontend/src/components/UI/Form/ComboBox/ComboBox.jsx
  frontend/src/components/Users/UserEmailComboBox/UserEmailComboBox.jsx
  frontend/src/components/Users/UserInfo/UserInfo.jsx
  frontend/src/components/Users/UserInfo/UserInfo.test.js
  frontend/src/pages/ErrorPage.jsx
  frontend/src/pages/agreements/CreateEditAgreement.jsx
  frontend/src/pages/agreements/EditAgreement.jsx
  frontend/src/pages/agreements/StepSelectProject.jsx
  frontend/src/pages/agreements/approve/ApproveAgreement.jsx
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.jsx
  frontend/src/pages/users/edit/EditUser.jsx
  frontend/src/test-utils.js
Labels: tech-debt

#3931 OPS-3904: agreement list filter by portfolio bug fix
  backend/ops_api/ops/schemas/budget_line_items.py
  backend/ops_api/ops/services/budget_line_items.py
  backend/ops_api/tests/ops/can/test_budget_line_item.py
  frontend/src/components/Portfolios/PortfoliosComboBox/PortfoliosComboBox.jsx
Labels: bug-high

#3946 fix: ♻️ display 'TBD' when totalFunding or totalReceived is 0
  frontend/src/components/CANs/CANTable/CANTableRow.jsx
  frontend/src/components/CANs/CANTable/CANTableRow.test.jsx
Labels: bug-medium

#3947 feat: ✨ enhance FE tooling
  .editorconfig
  .vscode/settings.json
  frontend/eslint.config.js
  frontend/package.json
  frontend/src/api/getCanFundingSummary.js
  frontend/src/api/opsAuthAPI.js
  frontend/src/api/postRefresh.js
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.jsx
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.test.jsx
  frontend/src/components/Agreements/DetailsTabs/DetailsTabs.module.scss
  frontend/src/components/Agreements/Documents/Document.js
  frontend/src/components/Agreements/Documents/Document.test.js
  frontend/src/components/Agreements/Documents/UploadDocument.jsx
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/components/Auth/MultiAuthSection.jsx
  frontend/src/components/Auth/auth.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.test.jsx
  frontend/src/components/CANs/CANBudgetForm/index.js
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTable.jsx
  frontend/src/components/CANs/CANDetailForm/index.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestList.test.jsx
  frontend/src/components/Portfolios/PortfolioSpending/PortfolioSpending.jsx
  frontend/src/components/UI/Cards/DocumentCard/styles.module.css
  frontend/src/components/UI/Cards/ProjectAgreementBLICard/ProjectAgreementBLICard.jsx
  frontend/src/components/UI/DataViz/LineGraph/ReverseLineGraph.jsx
  frontend/src/components/UI/DataViz/ResponsiveDonutWithInnerPercent/index.js
  frontend/src/components/UI/Footer/AgencyInfo.jsx
  frontend/src/components/UI/PaginationNav/PaginationNav.module.scss
  frontend/src/components/UI/USWDS/Tooltip/index.js
  frontend/src/constants.js
  frontend/src/hooks/use-sortable-data.hooks.js
  frontend/src/hooks/useNotifications.js
  frontend/src/hooks/useServicesComponents.hooks.js
  frontend/src/pages/agreements/list/AgreementsFilterButton/AgreementsFilterButton.hooks.js
  frontend/src/pages/agreements/list/AgreementsFilterButton/AgreementsFilterButton.jsx
  frontend/src/pages/agreements/list/AgreementsFilterTags/AgreementsFilterTags.hooks.js
  frontend/src/pages/agreements/list/AgreementsFilterTags/AgreementsFilterTags.jsx
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/budgetLines/list/BLIFilterButton.module.css
  frontend/src/pages/cans/list/CANFilterTags/CANFilterTags.hooks.js
  frontend/src/pages/cans/list/CanList.jsx
  frontend/src/store.js
  frontend/src/tests/data.js
  frontend/src/types/PortfolioTypes.d.ts
Labels: tech-debt

#3948 refactor: 💀 remove unused API files and tests
  frontend/src/api/getAgreements.js
  frontend/src/api/getAzureToken.js
  frontend/src/api/getCANFundingSummary.test.js
  frontend/src/api/getCanFiscalYear.js
  frontend/src/api/getCanFiscalYear.test.js
  frontend/src/api/getProcurementShopList.js
  frontend/src/api/getProcurementShopList.test.js
  frontend/src/api/getResearchProjects.js
  frontend/src/api/getResearchProjects.test.js
  frontend/src/api/patchAgreements.js
  frontend/src/api/patchAgreements.test.js
  frontend/src/api/postAgreements.js
  frontend/src/api/postAgreements.test.js
  frontend/src/api/postBliPackage.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
Labels: tech-debt

#3949 feat: ✨adds last update banner
  frontend/src/components/Layouts/DefaultLayout/DefaultLayout.jsx
  frontend/src/components/UI/Alert/SlimAlert.jsx
Labels: javascript

#3963 feat: adds copy to clipboard
  frontend/src/components/DebugCode/DebugCode.jsx
Labels: tech-debt

#3978 fix: simplify effect and update prop types
  frontend/src/components/Projects/ProjectSelectWithSummaryCard/ProjectSelectWithSummaryCard.jsx
Labels: bug-medium
