Repository HHS/OPRE-OPS, pull requests merged in 2025-03, with the labels that each got.

#3544 Hotfix: fixed can id filtering
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
Labels: bug

#3554 doc: update glossary
  frontend/cypress/e2e/helpCenter.cy.js
  frontend/src/pages/help/Feedback.jsx
  frontend/src/pages/help/Feedback.test.jsx
  frontend/src/pages/help/Glossary.jsx
  frontend/src/pages/help/HowToGuides.jsx
  frontend/src/pages/help/HowToGuides.test.jsx
Labels: documentation

#3546 feat: improve authentication and login ux
  frontend/README-AUTH.md
  frontend/bun.lockb
  frontend/package.json
  frontend/src/api/apiLogin.js
  frontend/src/api/apiLogin.test.js
  frontend/src/api/opsAuthAPI.js
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/components/Auth/MultiAuthSection.jsx
  frontend/src/components/Auth/MultiAuthSection.test.jsx
  frontend/src/components/Auth/MultiAuthSectionWithDebugging.jsx
  frontend/src/components/Auth/ProtectedRoute/ProtectedRoute.jsx
  frontend/src/components/Auth/auth.js
  frontend/src/components/Auth/auth.test.js
  frontend/src/mocks/README.md
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
  frontend/src/mocks/server.js
Labels: tech-debt

#3566 feat: enhance CAN table header tooltips and styling
  frontend/src/components/CANs/CANTable/CANTableHead.jsx
Labels: design

#3569 fix: add pagination fix for CAN list filtering
  frontend/cypress/e2e/canList.cy.js
  frontend/src/components/CANs/CANTable/CANTable.jsx
Labels: bug

#3567 docs: update howtoguides.jsx
  frontend/src/pages/help/HowToGuides.jsx
Labels: documentation

#3602 fix: fixed donut chart percent bug
  frontend/src/components/UI/DataViz/ResponsiveDonutWithInnerPercent/ResponsiveDonutWithInnerPercent.jsx
Labels: bug-low, OPS-support

#3581 OPS-3067/table export
  frontend/bun.lockb
  frontend/cypress/e2e/agreementList.cy.js
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/package.json
  frontend/src/api/opsAPI.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.test.jsx
  frontend/src/components/UI/FilterButton/FilterButton.jsx
  frontend/src/helpers/tableExport.helpers.js
  frontend/src/helpers/tableExport.helpers.test.js
  frontend/src/helpers/utils.js
  frontend/src/pages/agreements/list/AgreementsList.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Labels: javascript

#3618 feat: ✨ adds temp Homepage
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/approveCrossDivisionCRs.cy.js
  frontend/cypress/e2e/auth.cy.js
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/cypress/e2e/declineChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/loginPage.cy.js
  frontend/cypress/e2e/mainPage.cy.js
  frontend/cypress/e2e/reviewChangeRequestResponse.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtCardLevel.cy.js
  frontend/src/components/Auth/AuthSection.jsx
  frontend/src/components/Layouts/DefaultLayout/DefaultLayout.jsx
  frontend/src/components/UI/Alert/SlimAlert.jsx
  frontend/src/components/UI/Alert/SlimAlert.test.jsx
  frontend/src/components/UI/Cards/HoverCard/HoverCard.jsx
  frontend/src/components/UI/Cards/HoverCard/HoverCard.test.jsx
  frontend/src/components/UI/Cards/HoverCard/index.js
  frontend/src/components/UI/Header/GovBanner.jsx
  frontend/src/components/UI/Header/Header.jsx
  frontend/src/components/UI/Header/Menu.jsx
  frontend/src/components/UI/Header/NavMenu.jsx
  frontend/src/components/UI/Header/OPRE_Logo.png
  frontend/src/components/UI/Header/Search.jsx
  frontend/src/components/UI/Header/User.jsx
  frontend/src/images/approvals.svg
  frontend/src/images/autonomy.svg
  frontend/src/images/data-viz.svg
  frontend/src/images/flourish.svg
  frontend/src/images/gold-diagnal.png
  frontend/src/images/opre-logo.svg
  frontend/src/images/planning.svg
  frontend/src/images/transparency.svg
  frontend/src/index.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/home/index.js
Labels: javascript

#3634 style: update button text for budget line status change
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
Labels: javascript

#3633 feat: adds Error Boundary
  frontend/src/components/ErrorBoundary/ErrorBoundary.jsx
  frontend/src/components/ErrorBoundary/TestErrorComponent.jsx
  frontend/src/components/ErrorBoundary/index.js
  frontend/src/index.jsx
  frontend/src/pages/ErrorPage.jsx
Labels: javascript

#3653 Update bug template with new label
  .github/ISSUE_TEMPLATE/bugs.md
Labels: documentation
