Repository HHS/OPRE-OPS, pull requests merged in 2025-07, with the labels that each got.

#4065 feat: ✨adds last data update
  frontend/src/components/Layouts/DefaultLayout/DefaultLayout.jsx
  frontend/src/constants.js
  frontend/src/pages/home/release-notes/ReleaseNotes.test.jsx
  frontend/src/pages/home/release-notes/ReleaseNotesCards.jsx
  frontend/src/pages/home/release-notes/ReleaseNotesCards.test.jsx
Labels: javascript

#4083 feat: 🧪 adds cypress linting
  frontend/bun.lockb
  frontend/cypress/e2e/approveChangeRequestsAtAgreementLevel.cy.js
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/cypress/e2e/reviewChangeRequestsAtCardLevel.cy.js
  frontend/cypress/e2e/uploadDocument.cy.js
  frontend/eslint.config.js
  frontend/package.json
Labels: dependencies, javascript

#4073 fix: text not wrapping for agreement description and notes
  frontend/sass/uswds/styles.scss
  frontend/src/components/Agreements/AgreementsTable/AgreementTableRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/BLIDiffTable/BLIDiffRow.jsx
  frontend/src/components/BudgetLineItems/BLIReviewTable/BLIReviewRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/CANs/CANBudgetLineTable/CANBudgetLineTableRow.jsx
  frontend/src/components/ServicesComponents/ServicesComponentMetadata/ServicesComponentMetadata.jsx
  frontend/src/components/UI/Term/Term.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/uswds/css/styles.css
  frontend/src/uswds/css/styles.css.map
Labels: bug-low

#4086 fix: fixes Vite domain comparison
  frontend/vite.config.mjs
Labels: javascript, bug-low

#4089 feat: adds disabled state to proc shop select
  frontend/cypress/e2e/createAgreement.cy.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.test.js
  frontend/src/components/Agreements/ProcurementShopSelectWithFee/ProcurementShopSelectWithFee.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/pages/agreements/details/AgreementDetailsEdit.jsx
Labels: javascript

#4094 fix: procurement shop default option handling
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.hooks.js
  frontend/src/components/Agreements/ProcurementShopSelect/ProcurementShopSelect.jsx
  frontend/src/components/Projects/ProjectAgreementSummaryCard/ProjectAgreementSummaryCard.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
Labels: bug-low

#4081 feat: update Portfolio Detail page to show urls
  frontend/cypress/e2e/portfolioDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Portfolios/PortfolioHero/HeroDescription.jsx
  frontend/src/components/Portfolios/PortfolioHero/PortfolioHero.jsx
  frontend/src/components/Portfolios/PortfolioHero/index.js
  frontend/src/components/UI/Hero/Hero.jsx
  frontend/src/pages/portfolios/detail/PortfolioDetail.jsx
  frontend/src/pages/researchProjects/detail/ResearchProjectDetail.jsx
Labels: task

#4096 deps: upgrades eslint-plugin-vitest to latest
  frontend/bun.lockb
  frontend/eslint.config.js
  frontend/package.json
Labels: dependencies

#4109 feat: ✨ adds procurement shop CRs to Agreement Details page
  frontend/cypress.config.ci.js
  frontend/cypress.config.js
  frontend/cypress/e2e/editAgreementAsBasicUser.cy.js
  frontend/cypress/e2e/procurementShopChangeRequest.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/Agreements/AgreementEditor/AgreementEditForm.jsx
  frontend/src/components/Agreements/AgreementEditor/AgreementEditorContext.jsx
  frontend/src/helpers/agreement.helpers.js
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/utils.js
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/agreements/details/AgreementDetails.jsx
  frontend/src/pages/agreements/details/AgreementDetailsEdit.jsx
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/agreements/review/ReviewAgreement.hooks.js
  frontend/src/types/AgreementTypes.d.ts
  frontend/src/types/ChangeRequestsTypes.d.ts
Labels: javascript

#4116 fix: is obe is nullable and added new alembic script
  backend/alembic/versions/2025_07_07_0033-cac354dc41f5_add_change_requests_ops_events.py
  backend/alembic/versions/2025_07_17_1951-808b957abe3f_adding_is_obe_column_to_bli_table.py
  backend/models/budget_line_items.py
  backend/openapi.yml
Labels: bug-high

#4113 feat: 🐳 improve docker caching
  .github/actions/build-and-push/action.yaml
  frontend/Dockerfile.azure
  frontend/Dockerfile.dev
  frontend/docker-rebuild.sh
Labels: devex

#4121 Ops 4114/bug
  backend/data_tools/data/agreements_and_blin_data.json5
  backend/ops_api/tests/ops/budget_line_items/test_budget_line_item.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  backend/ops_api/tests/ops/funding_summary/test_portfolio_funding_summary.py
  frontend/cypress/e2e/agreementDetails.cy.js
  frontend/cypress/e2e/agreementDetailsEdit.cy.js
  frontend/cypress/e2e/budgetLineItemsList.cy.js
  frontend/cypress/e2e/canDetail.cy.js
  frontend/cypress/e2e/reviewAgreement.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBLIRow.test.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.jsx
  frontend/src/components/BudgetLineItems/AllBudgetLinesTable/AllBudgetLinesTable.test.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BLIRow.jsx
  frontend/src/components/BudgetLineItems/BudgetLinesTable/BudgetLinesTable.jsx
  frontend/src/helpers/budgetLines.helpers.js
  frontend/src/helpers/budgetLines.helpers.test.js
  frontend/src/helpers/utils.js
  frontend/src/pages/agreements/details/AgreementBudgetLines.jsx
  frontend/src/pages/budgetLines/list/BudgetLineItemList.jsx
Labels: bug-low

#4138 feat: ✨ adds procurement shop change requests card
  frontend/cypress/e2e/procurementShopChangeRequest.cy.js
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.hooks.jsx
  frontend/src/components/Agreements/AgreementChangesResponseAlert/AgreementChangesResponseAlert.jsx
  frontend/src/components/ChangeRequests/ChangeRequests.hooks.js
  frontend/src/components/ChangeRequests/ChangeRequestsList/ChangeRequestsList.jsx
  frontend/src/components/ChangeRequests/ProcurementShopReviewCard/ProcurementShopReviewCard.jsx
  frontend/src/components/ChangeRequests/ProcurementShopReviewCard/ProcurementShopReviewCard.test.jsx
  frontend/src/components/ChangeRequests/ProcurementShopReviewCard/index.js
  frontend/src/components/ChangeRequests/ReviewCard/ReviewCard.jsx
  frontend/src/components/ChangeRequests/TermTag/TermTag.jsx
  frontend/src/helpers/utils.js
  frontend/src/pages/agreements/details/Agreement.jsx
  frontend/src/types/ChangeRequestsTypes.d.ts
Labels: javascript
