Repository HHS/OPRE-OPS, pull requests merged in 2025-01, with the labels that each got.

#3246 feat: adds CAN Funding Received form
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.test.jsx
  frontend/src/components/CANs/CANBudgetForm/suite.js
  frontend/src/components/CANs/CANFundingReceivedForm/CanFundingReceivedForm.jsx
  frontend/src/components/CANs/CANFundingReceivedForm/CanFundingReceivedForm.test.jsx
  frontend/src/components/CANs/CANFundingReceivedForm/index.js
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTableRow.jsx
  frontend/src/components/UI/DataViz/LineGraph/LineGraph.jsx
  frontend/src/components/UI/DataViz/LineGraph/ReverseLineGraph.jsx
  frontend/src/components/UI/Form/CurrencyInput/CurrencyInput.jsx
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanFundingSuite.js
Labels: javascript

#3289 feat: add fiscal year calculations
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.helpers.js
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.helpers.test.js
Labels: javascript

#3300 feat: ✨ adds prev fy carry forward card
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
Labels: javascript

#3324 feat: table row editting and deleting
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/BudgetLineItems/ChangeIcons/ChangeIcons.jsx
  frontend/src/components/CANs/CANFundingReceivedForm/CanFundingReceivedForm.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.test.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTableRow.jsx
  frontend/src/components/CANs/CANTypes.d.ts
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanFundingSuite.js
Labels: javascript

#3334 feat: adds welcome modal to can funding received tab
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/components/CANs/CANBudgetByFYCard/CANBudgetByFYCard.jsx
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/components/CANs/CANFundingReceivedForm/CanFundingReceivedForm.jsx
  frontend/src/components/CANs/CANFundingReceivedTable/CANFundingReceivedTable.jsx
  frontend/src/components/UI/DataViz/LineBar/LineBar.jsx
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
Labels: javascript

#3347 feat: wip, enable infinite scroll
  frontend/src/components/CANs/CANDetailView/CANDetailView.jsx
  frontend/src/components/CANs/CANHistoryPanel/CANHistoryPanel.jsx
  frontend/src/pages/cans/detail/CanDetail.jsx
Labels: javascript

#3355 build: update jsdom to v26
  frontend/bun.lockb
  frontend/package.json
Labels: dependencies

#3345 feat: adds can history query and renders to can details page
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/api/opsAPI.js
  frontend/src/components/CANs/CANDetailView/CANDetailView.jsx
  frontend/src/components/CANs/CANDetailView/CANDetailView.test.jsx
  frontend/src/components/CANs/CANHistoryPanel/CANHistoryPanel.jsx
  frontend/src/components/CANs/CANHistoryPanel/index.js
  frontend/src/components/CANs/CANTypes.d.ts
  frontend/src/helpers/utils.js
  frontend/src/helpers/utils.test.js
  frontend/src/pages/agreements/details/AgreementDetailsView.jsx
  frontend/src/pages/cans/detail/CanDetail.jsx
Labels: javascript

#3361 feat: make nickname required for can patch
  backend/openapi.yml
  backend/ops_api/ops/schemas/cans.py
  backend/ops_api/tests/ops/can/test_can.py
Labels: python

#3377 feat: adds favicon
  frontend/index.html
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-96x96.png
  frontend/public/favicon.ico
  frontend/public/favicon.svg
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/web-app-manifest-192x192.png
  frontend/public/web-app-manifest-512x512.png
Labels: design

#3373 fix: CAN List filtering by Budget
  backend/ops_api/ops/services/can_funding_summary.py
  backend/ops_api/ops/utils/cans.py
  backend/ops_api/tests/ops/funding_summary/test_can_funding_summary.py
  frontend/cypress/e2e/canList.cy.js
  frontend/src/pages/cans/list/CanList.helpers.js
  frontend/src/pages/cans/list/CanList.helpers.test.js
  frontend/src/pages/cans/list/CanList.jsx
Labels: bug

#3381 refactor: update edit mode for CAN details
  frontend/cypress/e2e/canDetail.cy.js
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.jsx
  frontend/src/components/CANs/CANBudgetForm/CANBudgetForm.test.jsx
  frontend/src/components/CANs/CANHistoryPanel/CANHistoryPanel.jsx
  frontend/src/components/UI/Cards/BudgetCard/ReceivedFundingCard.jsx
  frontend/src/components/UI/Form/CurrencyInput/CurrencyInput.jsx
  frontend/src/pages/cans/detail/Can.hooks.js
  frontend/src/pages/cans/detail/Can.jsx
  frontend/src/pages/cans/detail/CanFunding.hooks.js
  frontend/src/pages/cans/detail/CanFunding.jsx
  frontend/src/pages/cans/detail/CanSpending.jsx
Labels: javascript
